### ISSUE TITLE
File upload form doesn't work because of BED-file-related error

### ISSUE THREAD

**Issue by adamnovak** [vgteam/sequenceTubeMap#159]
Related to #158, the file upload form doesn't actually seem to work on the demo server.

To reproduce:
1. Go to https://vgteam.github.io/sequenceTubeMap/
2. Set "Data" to "custom (file upload)"
3. For "xg file", upload the file at https://github.com/vgteam/sequenceTubeMap/raw/master/exampleData/backward.vg.xg
4. Set "Region" text box to "rev:1-10"
5. Hit "Go"
    
The page should draw a visualization, because "rev" is a path in that graph". But instead it complains about getting bad JSON back from the server.
    
If you start the inspector's Network panel before doing all this, you will see the `getChunkedData` request  it sent from the Go button click is for `{"region":"ref:1-11","xgFile":"1652731518175.xg","gbwtFile":"none","gamFile":"none","bedFile":"snp1kg-BRCA1.bed","dataPath":"upload"}`, which has a `bedFile` set, which I think is left over from the initial default view. It might or might not be causing part of the problem.

The response is a plain text message for a 500 error, which looks like it is trying to do something with that BED file but failing.

        ReferenceError: result is not defined
            at getBedRegions (/home/ubuntu/tubemaps/sequenceTubeMap/src/server.js:879:5)
            at api.post (/home/ubuntu/tubemaps/sequenceTubeMap/src/server.js:212:22)
            at Layer.handle [as handle_request] (/home/ubuntu/tubemaps/sequenceTubeMap/node_modules/express/lib/router/layer.js:95:5)
            at next (/home/ubuntu/tubemaps/sequenceTubeMap/node_modules/express/lib/router/route.js:137:13)
            at Route.dispatch (/home/ubuntu/tubemaps/sequenceTubeMap/node_modules/express/lib/router/route.js:112:3)
            at Layer.handle [as handle_request] (/home/ubuntu/tubemaps/sequenceTubeMap/node_modules/express/lib/router/layer.js:95:5)
            at /home/ubuntu/tubemaps/sequenceTubeMap/node_modules/express/lib/router/index.js:281:22
            at Function.process_params (/home/ubuntu/tubemaps/sequenceTubeMap/node_modules/express/lib/router/index.js:335:12)
            at next (/home/ubuntu/tubemaps/sequenceTubeMap/node_modules/express/lib/router/index.js:275:10)
            at api.use (/home/ubuntu/tubemaps/sequenceTubeMap/src/server.js:87:3)
            
So the server code probably needs fixing there, to not try and grab an undefined thing and use it, and possibly instead to kick back a properly-formatted error about not being able to do what it was asked to do with the BED file. The client probably needs to not be sending a `bedFile` at all here, since I didn't upload one.

**Comment by adamnovak** [comment]
I think that this will be fixed by https://github.com/vgteam/sequenceTubeMap/commit/88e26d445aaa2f8138dc4ca7b5fb56f4cdaaf81b#diff-79f4c7cdc0b026f6e556196f5911a449157807cffdb3f9d33f0b5404b4ffc2f3R899

**Comment by olivewong** [comment]
<img width="963" alt="Screen Shot 2022-05-26 at 2 58 25 PM" src="https://user-images.githubusercontent.com/11857485/170586791-9c23f888-80f2-404c-ad37-f62d3f770f4b.png">

This seems to be fixed on commit [5902a80](https://github.com/vgteam/sequenceTubeMap/pull/161/commits/5902a80697e4f4f1d25e31e0e77e0840e653d4aa) since the previous BED file is now cleared after selecting file upload from the data dropdown
