### ISSUE TITLE
vg chunk problem with newer vg docker image v1.5.0-2018-g71f96239-t119-run

### ISSUE THREAD

**Issue by Imoteph** [vgteam/sequenceTubeMap#22]
Hi,

I just played around with the provied dockerfile and changed in that process to a newer vg docker image which results into following error:
sh
```
./vg/vg chunk -x ./internalData/snp1kg-BRAC1.vg.xg -a ./internalData/NA12878-BRCA1.gam.index -g -A -p 17:1-101 -T -E regions.tsv | ./vg/vg view -j - >c5717fe0-dc25-11e7-8804-b9ee87b476a9.json
received request for filenames
Error: ENOENT: no such file or directory, scandir './mountedData/'
    at Error (native)
    at Object.fs.readdirSync (fs.js:961:18)
    at app.post (/usr/src/app/app.js:209:6)
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/src/app/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/src/app/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at /usr/src/app/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)
err data: error:[vg chunk] context expansion steps must be specified with -c/--context when chunking on paths
```

My assumption is that there was a change in vg chunk parameters handling logic. Unfortunately I am pretty new into vg and not sure how to set the correct value (in this case for c). Could someone tell me what value I should provide?

**Comment by wolfib** [comment]
You are correct, there were changes in vg chunk. I'm working on providing the appropriate update into the tube maps (dockerfile). For now you should be fine with specifying a value for -c for vg chunk (in /backend/app.js).

This is from @glennhickey  about the change to vg chunk:
-c (context expansion) was defaulting to 0.  This means it was pulling out only the nodes on the reference path (and not even any edges).  You'll need to specify a value for this to get any kind of variation out of the graph.  A very low value, say 5, should be fine for vcf-based graphs, but a higher value will be needed for more complex graphs.  You can probably put in something around 20 or so, but may be able to speed up by lowering.

**Comment by Imoteph** [comment]
Thx alot for providing the description. That helps a lot!
